### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Bondok6** [marilirulita/ToDoList#4]
# Hi @marilirulita 🙋‍♂️

## To Highlight

- Your project is amazing 👌
- Good job so far 🔥
- There are no technical errors, Everything is working fine

## Suggestions

- [Optional] I think it would be better to add a screenshot or a demo video of your project in the `README.md` file
- You can increase the width of `input` and remove the outline when you focus on the inputs. `outline: none`

<img src="https://media4.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif"/>

**Comment by gdumani** [comment]
**Nice code**
- Works as required
- Nice interface
- Code is easy to understand

**Comment by oyelakinG9** [comment]
![GOOD JOB 🎉](https://media.giphy.com/media/RgfGmnVvt8Pfy/giphy.gif)

**Comment by marilirulita** [comment]
Thanks for the comments!
